version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - API_KEY=${API_KEY}
      - ADMIN_ID=${ADMIN_ID}
      - CARD_DETAILS=${CARD_DETAILS}
      - MONGODB_URI=mongodb://mongo:27017/telegram_bot
      - DB_NAME=telegram_bot
      - TECNICAL_ADMIN_ID=${TECNICAL_ADMIN_ID}
      - NODE_ENV=production
    depends_on:
      - mongo
    volumes:
      - ./logs:/app/logs
    networks:
      - bot-network

  mongo:
    image: mongo:6
    environment:
      - MONGO_INITDB_DATABASE=telegram_bot
    volumes:
      - mongo-data:/data/db
    ports:
      - '27017:27017'
    networks:
      - bot-network

volumes:
  mongo-data:

networks:
  bot-network:
    driver: bridge
